In [24]:
import pymongo
import pandas as pd
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)
# Dependencies
from bs4 import BeautifulSoup
import requests
db=client.veilofignorancedb
db.veilofignorance.drop()
from splinter import Browser
from pprint import pprint

In [25]:
veil_df = pd.read_csv("AY_Prototype.csv") #csv file which you want to import
veil_df.head()
veil_df.columns = ['state_id', 'male', 'female', 'some_college_no_degree', 'associates_degree', 'bachelors_degree',
                    'graduate_or_professional_degree','18_to_24', '25_to_34', '35_to_44', '45_to_64', '65_and_over'] 
veil_df.head()

,state_id,male,female,some_college_no_degree,associates_degree,bachelors_degree,graduate_or_professional_degree,18_to_24,25_to_34,35_to_44,45_to_64,65_and_over
0,AL,18,21,67,80,28,55,36,13,21,74,18
1,AK,45,95,4,71,68,38,20,68,77,91,21
2,AZ,50,70,54,18,16,91,68,84,86,23,44
3,AR,40,17,42,49,50,45,64,58,6,6,3
4,CA,22,19,52,74,31,41,59,64,23,49,55

In [26]:
records = veil_df.to_dict(orient = 'records')
records

[{'state_id': 'AL',
  'male': 18,
  'female': 21,
  'some_college_no_degree': 67,
  'associates_degree': 80,
  'bachelors_degree': 28,
  'graduate_or_professional_degree': 55,
  '18_to_24': 36,
  '25_to_34': 13,
  '35_to_44': 21,
  '45_to_64': 74,
  '65_and_over': 18},
 {'state_id': 'AK',
  'male': 45,
  'female': 95,
  'some_college_no_degree': 4,
  'associates_degree': 71,
  'bachelors_degree': 68,
  'graduate_or_professional_degree': 38,
  '18_to_24': 20,
  '25_to_34': 68,
  '35_to_44': 77,
  '45_to_64': 91,
  '65_and_over': 21},
 {'state_id': 'AZ',
  'male': 50,
  'female': 70,
  'some_college_no_degree': 54,
  'associates_degree': 18,
  'bachelors_degree': 16,
  'graduate_or_professional_degree': 91,
  '18_to_24': 68,
  '25_to_34': 84,
  '35_to_44': 86,
  '45_to_64': 23,
  '65_and_over': 44},
 {'state_id': 'AR',
  'male': 40,
  'female': 17,
  'some_college_no_degree': 42,
  'associates_degree': 49,
  'bachelors_degree': 50,
  'graduate_or_professional_degree': 45,
  '18_to_24': 64,
  '25_to_34': 58,
  '35_to_44': 6,
  '45_to_64': 6,
  '65_and_over': 3},
 {'state_id': 'CA',
  'male': 22,
  'female': 19,
  'some_college_no_degree': 52,
  'associates_degree': 74,
  'bachelors_degree': 31,
  'graduate_or_professional_degree': 41,
  '18_to_24': 59,
  '25_to_34': 64,
  '35_to_44': 23,
  '45_to_64': 49,
  '65_and_over': 55},
 {'state_id': 'CO',
  'male': 13,
  'female': 5,
  'some_college_no_degree': 31,
  'associates_degree': 10,
  'bachelors_degree': 58,
  'graduate_or_professional_degree': 40,
  '18_to_24': 84,
  '25_to_34': 79,
  '35_to_44': 99,
  '45_to_64': 9,
  '65_and_over': 84},
 {'state_id': 'CT',
  'male': 56,
  'female': 5,
  'some_college_no_degree': 73,
  'associates_degree': 63,
  'bachelors_degree': 61,
  'graduate_or_professional_degree': 58,
  '18_to_24': 9,
  '25_to_34': 25,
  '35_to_44': 6,
  '45_to_64': 55,
  '65_and_over': 1},
 {'state_id': 'DE',
  'male': 51,
  'female': 79,
  'some_college_no_degree': 99,
  'associates_degree': 17,
  'bachelors_degree': 37,
  'graduate_or_professional_degree': 55,
  '18_to_24': 22,
  '25_to_34': 77,
  '35_to_44': 59,
  '45_to_64': 66,
  '65_and_over': 70},
 {'state_id': 'DC',
  'male': 44,
  'female': 53,
  'some_college_no_degree': 54,
  'associates_degree': 64,
  'bachelors_degree': 50,
  'graduate_or_professional_degree': 90,
  '18_to_24': 69,
  '25_to_34': 76,
  '35_to_44': 32,
  '45_to_64': 14,
  '65_and_over': 13},
 {'state_id': 'FL',
  'male': 30,
  'female': 54,
  'some_college_no_degree': 42,
  'associates_degree': 28,
  'bachelors_degree': 45,
  'graduate_or_professional_degree': 20,
  '18_to_24': 56,
  '25_to_34': 1,
  '35_to_44': 79,
  '45_to_64': 4,
  '65_and_over': 98},
 {'state_id': 'GA',
  'male': 28,
  'female': 6,
  'some_college_no_degree': 53,
  'associates_degree': 6,
  'bachelors_degree': 66,
  'graduate_or_professional_degree': 5,
  '18_to_24': 33,
  '25_to_34': 52,
  '35_to_44': 86,
  '45_to_64': 31,
  '65_and_over': 59},
 {'state_id': 'HI',
  'male': 67,
  'female': 88,
  'some_college_no_degree': 59,
  'associates_degree': 86,
  'bachelors_degree': 9,
  'graduate_or_professional_degree': 16,
  '18_to_24': 60,
  '25_to_34': 1,
  '35_to_44': 73,
  '45_to_64': 99,
  '65_and_over': 68},
 {'state_id': 'ID',
  'male': 18,
  'female': 45,
  'some_college_no_degree': 50,
  'associates_degree': 10,
  'bachelors_degree': 39,
  'graduate_or_professional_degree': 54,
  '18_to_24': 44,
  '25_to_34': 36,
  '35_to_44': 15,
  '45_to_64': 10,
  '65_and_over': 70},
 {'state_id': 'IL',
  'male': 92,
  'female': 13,
  'some_college_no_degree': 25,
  'associates_degree': 3,
  'bachelors_degree': 10,
  'graduate_or_professional_degree': 53,
  '18_to_24': 9,
  '25_to_34': 14,
  '35_to_44': 72,
  '45_to_64': 11,
  '65_and_over': 13},
 {'state_id': 'IN',
  'male': 8,
  'female': 44,
  'some_college_no_degree': 73,
  'associates_degree': 100,
  'bachelors_degree': 80,
  'graduate_or_professional_degree': 29,
  '18_to_24': 84,
  '25_to_34': 53,
  '35_to_44': 97,
  '45_to_64': 4,
  '65_and_over': 48},
 {'state_id': 'IA',
  'male': 62,
  'female': 74,
  'some_college_no_degree': 48,
  'associates_degree': 99,
  'bachelors_degree': 28,
  'graduate_or_professional_degree': 38,
  '18_to_24': 18,
  '25_to_34': 63,
  '35_to_44': 68,
  '45_to_64': 19,
  '65_and_over': 35},
 {'state_id': 'KS',
  'male': 72,
  'female': 58,
  'some_college_no_degree': 55,
  'associates_degree': 44,
  'bachelors_degree': 1,
  'graduate_or_professional_degree': 3,
  '18_to_24': 76,
  '25_to_34': 94,
  '35_to_44': 20,
  '45_to_64': 65,
  '65_and_over': 60},
 {'state_id': 'KY',
  'male': 29,
  'female': 48,
  'some_college_no_degree': 21,
  'associates_degree': 54,
  'bachelors_degree': 62,
  'graduate_or_professional_degree': 65,
  '18_to_24': 93,
  '25_to_34': 55,
  '35_to_44': 49,
  '45_to_64': 80,
  '65_and_over': 63},
 {'state_id': 'LA',
  'male': 19,
  'female': 22,
  'some_college_no_degree': 59,
  'associates_degree': 1,
  'bachelors_degree': 80,
  'graduate_or_professional_degree': 14,
  '18_to_24': 40,
  '25_to_34': 47,
  '35_to_44': 59,
  '45_to_64': 7,
  '65_and_over': 59},
 {'state_id': 'ME',
  'male': 44,
  'female': 13,
  'some_college_no_degree': 26,
  'associates_degree': 92,
  'bachelors_degree': 85,
  'graduate_or_professional_degree': 96,
  '18_to_24': 50,
  '25_to_34': 25,
  '35_to_44': 83,
  '45_to_64': 48,
  '65_and_over': 43},
 {'state_id': 'MD',
  'male': 87,
  'female': 84,
  'some_college_no_degree': 57,
  'associates_degree': 72,
  'bachelors_degree': 48,
  'graduate_or_professional_degree': 44,
  '18_to_24': 29,
  '25_to_34': 84,
  '35_to_44': 74,
  '45_to_64': 48,
  '65_and_over': 81},
 {'state_id': 'MA',
  'male': 61,
  'female': 8,
  'some_college_no_degree': 12,
  'associates_degree': 97,
  'bachelors_degree': 96,
  'graduate_or_professional_degree': 89,
  '18_to_24': 52,
  '25_to_34': 17,
  '35_to_44': 93,
  '45_to_64': 21,
  '65_and_over': 82},
 {'state_id': 'MI',
  'male': 37,
  'female': 34,
  'some_college_no_degree': 70,
  'associates_degree': 16,
  'bachelors_degree': 1,
  'graduate_or_professional_degree': 98,
  '18_to_24': 76,
  '25_to_34': 6,
  '35_to_44': 71,
  '45_to_64': 34,
  '65_and_over': 39},
 {'state_id': 'MN',
  'male': 26,
  'female': 50,
  'some_college_no_degree': 22,
  'associates_degree': 38,
  'bachelors_degree': 46,
  'graduate_or_professional_degree': 6,
  '18_to_24': 100,
  '25_to_34': 7,
  '35_to_44': 5,
  '45_to_64': 59,
  '65_and_over': 58},
 {'state_id': 'MS',
  'male': 16,
  'female': 41,
  'some_college_no_degree': 36,
  'associates_degree': 78,
  'bachelors_degree': 72,
  'graduate_or_professional_degree': 95,
  '18_to_24': 93,
  '25_to_34': 45,
  '35_to_44': 5,
  '45_to_64': 82,
  '65_and_over': 59},
 {'state_id': 'MO',
  'male': 71,
  'female': 47,
  'some_college_no_degree': 98,
  'associates_degree': 43,
  'bachelors_degree': 2,
  'graduate_or_professional_degree': 54,
  '18_to_24': 5,
  '25_to_34': 45,
  '35_to_44': 97,
  '45_to_64': 28,
  '65_and_over': 64},
 {'state_id': 'MT',
  'male': 90,
  'female': 19,
  'some_college_no_degree': 67,
  'associates_degree': 84,
  'bachelors_degree': 20,
  'graduate_or_professional_degree': 7,
  '18_to_24': 44,
  '25_to_34': 54,
  '35_to_44': 62,
  '45_to_64': 40,
  '65_and_over': 88},
 {'state_id': 'NE',
  'male': 5,
  'female': 72,
  'some_college_no_degree': 89,
  'associates_degree': 94,
  'bachelors_degree': 78,
  'graduate_or_professional_degree': 2,
  '18_to_24': 59,
  '25_to_34': 41,
  '35_to_44': 49,
  '45_to_64': 45,
  '65_and_over': 98},
 {'state_id': 'NV',
  'male': 25,
  'female': 69,
  'some_college_no_degree': 51,
  'associates_degree': 46,
  'bachelors_degree': 22,
  'graduate_or_professional_degree': 34,
  '18_to_24': 49,
  '25_to_34': 95,
  '35_to_44': 1,
  '45_to_64': 46,
  '65_and_over': 57},
 {'state_id': 'NH',
  'male': 60,
  'female': 94,
  'some_college_no_degree': 34,
  'associates_degree': 59,
  'bachelors_degree': 5,
  'graduate_or_professional_degree': 46,
  '18_to_24': 3,
  '25_to_34': 61,
  '35_to_44': 10,
  '45_to_64': 34,
  '65_and_over': 14},
 {'state_id': 'NJ',
  'male': 5,
  'female': 91,
  'some_college_no_degree': 85,
  'associates_degree': 97,
  'bachelors_degree': 37,
  'graduate_or_professional_degree': 60,
  '18_to_24': 16,
  '25_to_34': 79,
  '35_to_44': 37,
  '45_to_64': 36,
  '65_and_over': 13},
 {'state_id': 'NM',
  'male': 69,
  'female': 44,
  'some_college_no_degree': 21,
  'associates_degree': 76,
  'bachelors_degree': 84,
  'graduate_or_professional_degree': 31,
  '18_to_24': 77,
  '25_to_34': 10,
  '35_to_44': 1,
  '45_to_64': 78,
  '65_and_over': 69},
 {'state_id': 'NY',
  'male': 25,
  'female': 100,
  'some_college_no_degree': 76,
  'associates_degree': 40,
  'bachelors_degree': 3,
  'graduate_or_professional_degree': 75,
  '18_to_24': 16,
  '25_to_34': 31,
  '35_to_44': 5,
  '45_to_64': 53,
  '65_and_over': 27},
 {'state_id': 'NC',
  'male': 63,
  'female': 57,
  'some_college_no_degree': 51,
  'associates_degree': 94,
  'bachelors_degree': 59,
  'graduate_or_professional_degree': 44,
  '18_to_24': 68,
  '25_to_34': 92,
  '35_to_44': 36,
  '45_to_64': 25,
  '65_and_over': 35},
 {'state_id': 'ND',
  'male': 8,
  'female': 45,
  'some_college_no_degree': 30,
  'associates_degree': 14,
  'bachelors_degree': 2,
  'graduate_or_professional_degree': 39,
  '18_to_24': 98,
  '25_to_34': 10,
  '35_to_44': 91,
  '45_to_64': 90,
  '65_and_over': 57},
 {'state_id': 'OH',
  'male': 26,
  'female': 78,
  'some_college_no_degree': 85,
  'associates_degree': 82,
  'bachelors_degree': 93,
  'graduate_or_professional_degree': 24,
  '18_to_24': 43,
  '25_to_34': 31,
  '35_to_44': 25,
  '45_to_64': 55,
  '65_and_over': 80},
 {'state_id': 'OK',
  'male': 95,
  'female': 21,
  'some_college_no_degree': 64,
  'associates_degree': 28,
  'bachelors_degree': 41,
  'graduate_or_professional_degree': 39,
  '18_to_24': 75,
  '25_to_34': 47,
  '35_to_44': 22,
  '45_to_64': 48,
  '65_and_over': 68},
 {'state_id': 'OR',
  'male': 93,
  'female': 33,
  'some_college_no_degree': 53,
  'associates_degree': 77,
  'bachelors_degree': 91,
  'graduate_or_professional_degree': 49,
  '18_to_24': 96,
  '25_to_34': 84,
  '35_to_44': 49,
  '45_to_64': 89,
  '65_and_over': 13},
 {'state_id': 'PA',
  'male': 73,
  'female': 78,
  'some_college_no_degree': 84,
  'associates_degree': 11,
  'bachelors_degree': 77,
  'graduate_or_professional_degree': 84,
  '18_to_24': 10,
  '25_to_34': 85,
  '35_to_44': 97,
  '45_to_64': 25,
  '65_and_over': 76},
 {'state_id': 'RI',
  'male': 19,
  'female': 26,
  'some_college_no_degree': 85,
  'associates_degree': 37,
  'bachelors_degree': 50,
  'graduate_or_professional_degree': 30,
  '18_to_24': 25,
  '25_to_34': 28,
  '35_to_44': 61,
  '45_to_64': 92,
  '65_and_over': 42},
 {'state_id': 'SC',
  'male': 80,
  'female': 55,
  'some_college_no_degree': 36,
  'associates_degree': 94,
  'bachelors_degree': 8,
  'graduate_or_professional_degree': 67,
  '18_to_24': 40,
  '25_to_34': 14,
  '35_to_44': 10,
  '45_to_64': 94,
  '65_and_over': 87},
 {'state_id': 'SD',
  'male': 54,
  'female': 79,
  'some_college_no_degree': 47,
  'associates_degree': 26,
  'bachelors_degree': 79,
  'graduate_or_professional_degree': 84,
  '18_to_24': 74,
  '25_to_34': 52,
  '35_to_44': 29,
  '45_to_64': 1,
  '65_and_over': 14},
 {'state_id': 'TN',
  'male': 19,
  'female': 12,
  'some_college_no_degree': 61,
  'associates_degree': 3,
  'bachelors_degree': 79,
  'graduate_or_professional_degree': 92,
  '18_to_24': 93,
  '25_to_34': 9,
  '35_to_44': 12,
  '45_to_64': 63,
  '65_and_over': 12},
 {'state_id': 'TX',
  'male': 62,
  'female': 77,
  'some_college_no_degree': 17,
  'associates_degree': 51,
  'bachelors_degree': 97,
  'graduate_or_professional_degree': 29,
  '18_to_24': 67,
  '25_to_34': 68,
  '35_to_44': 96,
  '45_to_64': 90,
  '65_and_over': 27},
 {'state_id': 'UT',
  'male': 41,
  'female': 48,
  'some_college_no_degree': 60,
  'associates_degree': 31,
  'bachelors_degree': 64,
  'graduate_or_professional_degree': 95,
  '18_to_24': 100,
  '25_to_34': 92,
  '35_to_44': 36,
  '45_to_64': 13,
  '65_and_over': 81},
 {'state_id': 'VT',
  'male': 27,
  'female': 4,
  'some_college_no_degree': 31,
  'associates_degree': 90,
  'bachelors_degree': 95,
  'graduate_or_professional_degree': 89,
  '18_to_24': 79,
  '25_to_34': 7,
  '35_to_44': 44,
  '45_to_64': 77,
  '65_and_over': 88},
 {'state_id': 'VA',
  'male': 75,
  'female': 95,
  'some_college_no_degree': 97,
  'associates_degree': 77,
  'bachelors_degree': 31,
  'graduate_or_professional_degree': 9,
  '18_to_24': 33,
  '25_to_34': 87,
  '35_to_44': 42,
  '45_to_64': 47,
  '65_and_over': 46},
 {'state_id': 'WA',
  'male': 27,
  'female': 1,
  'some_college_no_degree': 32,
  'associates_degree': 37,
  'bachelors_degree': 74,
  'graduate_or_professional_degree': 14,
  '18_to_24': 57,
  '25_to_34': 12,
  '35_to_44': 88,
  '45_to_64': 80,
  '65_and_over': 99},
 {'state_id': 'WV',
  'male': 27,
  'female': 53,
  'some_college_no_degree': 69,
  'associates_degree': 60,
  'bachelors_degree': 57,
  'graduate_or_professional_degree': 73,
  '18_to_24': 63,
  '25_to_34': 62,
  '35_to_44': 21,
  '45_to_64': 63,
  '65_and_over': 36},
 {'state_id': 'WI',
  'male': 88,
  'female': 69,
  'some_college_no_degree': 75,
  'associates_degree': 96,
  'bachelors_degree': 78,
  'graduate_or_professional_degree': 6,
  '18_to_24': 88,
  '25_to_34': 62,
  '35_to_44': 36,
  '45_to_64': 84,
  '65_and_over': 21},
 {'state_id': 'WY',
  'male': 67,
  'female': 72,
  'some_college_no_degree': 100,
  'associates_degree': 25,
  'bachelors_degree': 77,
  'graduate_or_professional_degree': 25,
  '18_to_24': 44,
  '25_to_34': 56,
  '35_to_44': 52,
  '45_to_64': 27,
  '65_and_over': 30},
 {'state_id': 'PR',
  'male': 94,
  'female': 45,
  'some_college_no_degree': 32,
  'associates_degree': 68,
  'bachelors_degree': 100,
  'graduate_or_professional_degree': 9,
  '18_to_24': 13,
  '25_to_34': 34,
  '35_to_44': 87,
  '45_to_64': 77,
  '65_and_over': 34}]

In [27]:
# Creates a collection in the database and inserts documents
db.veilofignorance.insert_many(records)